# Generated by Django 3.0 on 2020-01-03 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200103_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='filename',
        ),
    ]
